version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    
    environment:
      MYSQL_DATABASE: ingenieriadb
      MYSQL_PASSWORD: widowmaker
      MYSQL_ROOT_PASSWORD: widowmaker
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - kafka-net
      - mired

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "181.205.220.123:80:80"
      - "181.205.220.123:443:443"

      - "181.205.220.122:80:80"
      - "181.205.220.122:443:443"
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=false"
      - "--api.insecure=false"
      
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=gm2_mired"

      # ACME / Let's Encrypt (resolver 'le')
      - "--certificatesresolvers.le.acme.email=web@equibiomedic.co"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"

    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/traefik:/letsencrypt
    networks:
      - mired

  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    restart: always
    ports:
      - "181.205.220.123:53:53/udp" 
      - "181.205.220.123:53:53/tcp"
    volumes:
      - ./bind/named.conf:/etc/bind/named.conf
      - ./bind/zones:/var/lib/bind
    networks:
      - mired

  www:
    restart: always
    build: .
    volumes:
      - /media/backup/server/webApplications:/var/www/html
      - ./apache2:/etc/apache2
    networks:
      - mired
    labels:
      - "traefik.enable=true"

      # Router HTTPS principal: www.equibiomedic.co
      - "traefik.http.routers.www.rule=Host(`www.equibiomedic.co`)"
      - "traefik.http.routers.www.entrypoints=websecure"
      - "traefik.http.routers.www.tls=true"
      - "traefik.http.routers.www.tls.certresolver=le"
      - "traefik.http.services.www.loadbalancer.server.port=80"

      # Router HTTP solo para redirigir a HTTPS
      - "traefik.http.routers.www-http.rule=Host(`www.equibiomedic.co`)"
      - "traefik.http.routers.www-http.entrypoints=web"
      - "traefik.http.routers.www-http.middlewares=redirect-to-https"

      # equibiomedic.co -> redirige a https://www.equibiomedic.co
      - "traefik.http.routers.www-root.rule=Host(`equibiomedic.co`)"
      - "traefik.http.routers.www-root.entrypoints=websecure"
      - "traefik.http.routers.www-root.tls=true"
      - "traefik.http.routers.www-root.tls.certresolver=le"
      - "traefik.http.routers.www-root.middlewares=redirect-to-www"

      # Middleware: equibiomedic.co -> https://www.equibiomedic.co
      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https?://equibiomedic\\.co(.*)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.equibiomedic.co$$1"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"

      # Middleware: http -> https para www.equibiomedic.co
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: widowmaker
      MYSQL_ROOT_PASSWORD: widowmaker
    networks:
      - mired

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,PLAINTEXT_EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_EXTERNAL://127.0.0.1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  notification-service:
    build:
      context: /media/backup/server/GM2/notifications
      dockerfile: Dockerfile
    container_name: notification-service
    restart: always
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka-net

  kafdrop:
    image: obsidiandynamics/kafdrop:3.30.0
    container_name: kafdrop
    restart: always
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka-net

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9100:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - mired
#ai

  redis-insight:
    build:
      context: .
      dockerfile: Dockerfile.redisinsight
    image: redisinsight-custom
    container_name: redis_insight
    restart: always
    ports:
      - "8001:5540"
    depends_on:
      - redis
    networks:
      - mired

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    networks:
      - mired
    environment:
      REDIS_PASSWORD: Elian2020#   # recuerda requirepass si quieres que sea efectivo

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "8075:6333"
      - "8076:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__API_KEY: Elian2020#
      QDRANT__SERVICE__READ_ONLY_API_KEY: Elian2020#
    networks:
      - mired

  n8n:
    image: n8nio/n8n:latest
    container_name: n8nserver.com
    restart: always
    environment:
      - N8N_HOST=autobot.cloudfly.com.co
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - WEBHOOK_URL=https://autobot.cloudfly.com.co/
      - N8N_EDITOR_BASE_URL=https://autobot.cloudfly.com.co
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=true
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - qdrant
      - redis
      - postgresql
      - evolution-api
    networks:
      - mired
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`autobot.cloudfly.com.co`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=le"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  postgresql:
    image: pgvector/pgvector:pg15
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_DB: chatbotdb
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mired
  
  evolution-api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api
    restart: always
    ports:
      - "8082:8080"  # Puerto para acceso local/desarrollo
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - mired
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eapi.rule=Host(`eapi.cloudfly.com.co`)"
      - "traefik.http.routers.eapi.entrypoints=websecure"
      - "traefik.http.routers.eapi.tls.certresolver=le"
      - "traefik.http.services.eapi.loadbalancer.server.port=8080"

  chatwoot:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot
    restart: always
    command: /bin/sh -lc "bundle exec rails db:chatwoot_prepare && mkdir -p tmp/pids && bundle exec puma -C config/puma.rb"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatwoot.rule=Host(`chatcenter.cloudfly.com.co`)"
      - "traefik.http.routers.chatwoot.entrypoints=websecure"
      - "traefik.http.routers.chatwoot.tls.certresolver=le"
      - "traefik.http.services.chatwoot.loadbalancer.server.port=3000"
    env_file:
      - .env.chatwoot
    volumes:
      - chatwoot_storage:/app/storage
    depends_on:
      - postgresql
      - redis
    networks:
      - mired

  chatwoot-worker:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot_worker
    restart: always
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: "44d4f95c1b13aa70fd34dd6453a121fd962d9c1b748b28f21ac36cd1f481714a"
      FRONTEND_URL: "https://chatcenter.cloudfly.com.co"
      ACTIVE_STORAGE_SERVICE: "local"
      DATABASE_URL: "postgres://chatbot_user:chatbot_pass@postgresql:5432/chatwoot_production"
      REDIS_URL: "redis://redis:6379/1"
      DEFAULT_LOCALE: "es"
    volumes:
      - chatwoot_storage:/app/storage
    depends_on:
      - postgresql
      - redis
      - chatwoot
    networks:
      - mired

volumes:
  db_data:
  db_data2:
  persistent:
  portainer_data:
  backup:

  n8n_data:
  qdrant_data:
  postgres_data:
  mongo_evolution_data:
  evolution_instances:
  chatwoot_storage:
  persistent_master:

networks:
  kafka-net:
    name: gm2_kafka-net
    driver: bridge
  mired:
    name: gm2_mired
    driver: bridge
