version: "3.9"

services:
  # ================================
  #  DB DESARROLLO
  # ================================
  db_develop:
    image: mysql:8.0
    container_name: mysql_develop
    restart: always
    ports:
      - "3307:3306"              # no choca con prod (3306)
    environment:
      MYSQL_DATABASE: GM2_develop
      MYSQL_ROOT_PASSWORD: widowmaker
    volumes:
      - persistent_develop:/var/lib/mysql
    networks:
      - kafka-net-dev
      - mired

  # ================================
  #  ZOOKEEPER DESARROLLO
  # ================================
  zookeeper-dev:
    image: confluentinc/cp-zookeeper:7.4.0
    restart: always
    ports:
      - "22181:2181"             # distinto a prod (2181->2181)
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net-dev

  # ================================
  #  KAFKA DESARROLLO
  # ================================
  kafka-dev:
    image: confluentinc/cp-kafka:7.4.0
    restart: always
    ports:
      - "9094:9092"              # distinto a prod (9092->9092)
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-dev:2181
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka-dev:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net-dev

  # ================================
  #  BACKEND SPRING DESARROLLO
  # ================================
  backend-spring_develop:
    build:
      context: /media/backup/server/GM2/backend
      dockerfile: Dockerfile
    depends_on: 
      - db_develop
      - kafka-dev
    restart: always
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-dev:9092
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: db_develop
      DB_PORT: 3306
      DB_DATABASE: GM2_develop
      DB_USERNAME: root
      DB_PASSWORD: widowmaker
      NEXT_FRONTEND_URL: https://gm2dev.equibiomedic.co
      CORS_ALLOWED_ORIGIN: http://localhost:3000,https://gm2dev.equibiomedic.co
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 200MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 200MB
    volumes:
      - ./media/documents:/app/documents
      - ./media/firma_soporte:/app/firma_soporte
      - ./media/firmas/:/app/firmas
      - ./media/images:/app/images
      - ./media/uploads:/app/uploads
    networks:
      - kafka-net-dev
      - mired
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apidev.rule=Host(`apidev.equibiomedic.co`)"
      - "traefik.http.routers.apidev.entrypoints=websecure"
      - "traefik.http.routers.apidev.tls.certresolver=le"
      - "traefik.http.services.apidev.loadbalancer.server.port=8080"


  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11438:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - mired

  # ================================
  #  FRONTEND GM2 DESARROLLO
  # ================================
  gm2_develop:
    container_name: gm2_app_develop
    build:
      context: /media/backup/server/GM2/frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://apidev.equibiomedic.co
        - NEXT_FRONTEND_URL=https://gm2dev.equibiomedic.co
    environment:
      - NEXT_PUBLIC_API_URL=https://apidev.equibiomedic.co
      - NEXT_FRONTEND_URL=https://gm2dev.equibiomedic.co
    restart: always
    networks:
      - mired
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gm2-dev.rule=Host(`gm2dev.equibiomedic.co`)"
      - "traefik.http.routers.gm2-dev.entrypoints=websecure"
      - "traefik.http.routers.gm2-dev.tls.certresolver=le"
      - "traefik.http.services.gm2-dev.loadbalancer.server.port=3000"

volumes:
  persistent_develop:

networks:
  # Red interna SOLO para Kafka/Zoo/DB de dev
  kafka-net-dev:
    driver: bridge

  # Red compartida con Traefik de PRODUCCIÓN
  mired:
    external: true
    name: gm2_mired 
