spring.application.name=service
spring.kafka.bootstrapServers=127.0.0.1:9092


spring.mail.host=mail.cloudfly.com.co
spring.mail.port=587
spring.mail.username=gm2@yunismedical.com
spring.mail.password=Elian2020#
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
spring.mail.properties.mail.smtp.socketFactory.class=
spring.mail.properties.mail.smtp.socketFactory.fallback=true
server.port=8082